# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy UI to Fly
on:
  push:
    branches:
      - main
    paths:
      - 'apps/ui/**'
      - '.github/workflows/fly-deploy-ui.yml'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy:
    name: Deploy UI
    runs-on: ubuntu-latest
    concurrency: deploy-ui-group
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --config apps/ui/fly.toml --dockerfile apps/ui/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
