# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy API to Fly
on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - '.github/workflows/fly-deploy-api.yml'

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    concurrency: deploy-api-group
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --config apps/api/fly.toml --dockerfile apps/api/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_API }} 
